export const GET_DATA_LOADING = "GET_DATA_LOADING"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FAILURE = "GET_DATA_FAILURE"

export const POST_DATA_LOADING = "POST_DATA_LOADING"
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS"
export const POST_DATA_FAILURE = "POST_DATA_FAILURE"

export const EDIT_DATA_LOADING = "EDIT_DATA_LOADING"
export const EDIT_DATA_SUCCESS = "EDIT_DATA_SUCCESS"
export const EDIT_DATA_FAILURE = "EDIT_DATA_FAILURE"

export const DELETE_DATA_LOADING = "DELETE_DATA_LOADING"
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS"
export const DELETE_DATA_FAILURE = "DELETE_DATA_FAILURE"

export const GET_SINGLE_DATA_LOADING = "GET_SINGLE_DATA_LOADING"
export const GET_SINGLE_DATA_SUCCESS = "GET_SINGLE_DATA_SUCCESS"
export const GET_SINGLE_DATA_FAILURE = "GET_SINGLE_DATA_FAILURE"

